version: "3"

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=elara
      - MYSQL_ROOT_PASSWORD=1234

